webapp, rest api compatibility changes
setnicka/ulozto-downloader pull request #115
Opened 2022-09-19 00:26 UTC by SpiReCZ

This is PR for core compatibility changes to enable development of other Frontend implementations like Webapp or REST API. Example implementation of REST API: https://github.com/SpiReCZ/ulozto-streamer/tree/ulozto-streamer-sb

Things i've changed in uldlib:
- **.udown is needed** to read sequentially the downloaded file while downloading it and after download has finished (SegFileReader implementation).
- **Access to Tor instance is needed** for correct handling of startup/shutdown of it`s process.
- **Access to some Downloader properties** of the downloaded file needs to be available.
- Tor data dir should be configurable since it the base folder can be set to /tmp
- sys.exit(1) is not friendly to Web App, exception should be raised instead (not all instances were fixed/changed, only some that made the most problems)
- **Not every Frontend supports prompt**
- Other minor stuff
- SegFile parent class created (needed for SegFileReader)

2022-10-14 16:04 UTC, setnicka commented
Sorry for the delay, I will try to review this in the following week.

2022-10-27 22:38 UTC, setnicka requested changes
I review the changes, it looks good :) Some minor issues in the comments.

Also please rebase on the current master and include a summary of changed things in the commit message (like "Things i've changed in uldlib:" in the pull request description). Thank you.

2022-10-28 14:56 UTC, SpiReCZ commented on uldlib/downloader.py
> +            # self.stop_captcha.set() # this effectively shutdowns fastapi server if triggered
I think this a left over of previous version before Frontend and threading usage. I tested it without this change and now it works.

2022-10-28 14:58 UTC, SpiReCZ commented
added fix: argument had a wrong type (left over before Frontend)

2022-10-28 15:47 UTC, SpiReCZ commented
The changes are ready to be merged.

2022-10-28 17:24 UTC, setnicka commented
Thank you, merging now :)

I will publish (and upload to PyPI) a new version of the ulozto-downloader with these changes later this weekend.

2022-10-28 17:24 UTC, setnicka approved these changes

2022-10-28 17:24 UTC, merged

2022-10-28 19:47 UTC, SpiReCZ commented
> Thank you, merging now :)
> 
> I will publish (and upload to PyPI) a new version of the ulozto-downloader with these changes later this weekend.

Thx, i already decoupled my source code and it is ready to use the downloader as a dependency.